# Generated by Django 6.0.1 on 2026-02-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dept_tbl_reg_tbl_doctor_tbl_book_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_tbl',
            name='district',
        ),
        migrations.RemoveField(
            model_name='book_tbl',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='book_tbl',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book_tbl',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='book_tbl',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='book_tbl',
            name='name',
        ),
        migrations.AddField(
            model_name='book_tbl',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.doctor_tbl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_tbl',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_tbl',
            name='test',
            field=models.CharField(max_length=100),
        ),
    ]
