# Generated by Django 6.0.1 on 2026-02-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book_tbl_district_remove_book_tbl_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_tbl',
            name='user',
        ),
    ]
