# Generated by Django 6.0.1 on 2026-02-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_book_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tbl',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.reg_tbl'),
            preserve_default=False,
        ),
    ]
