# Generated by Django 6.0.1 on 2026-01-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_tbl',
            name='dept_name',
        ),
        migrations.DeleteModel(
            name='book_tbl',
        ),
        migrations.DeleteModel(
            name='reg_tbl',
        ),
        migrations.DeleteModel(
            name='Dept_tbl',
        ),
        migrations.DeleteModel(
            name='Doctor_tbl',
        ),
    ]
